// The data-broker catalog, transcribed from the "🎯 Master Tracker" tab of
// Data_Broker_Removal_Tracker.xlsx (93 brokers). Seeded into `dataSources` by
// `dataSources:seedBrokers`. Static reference data — per-user removal state lives in
// `brokerExposures`.

export type BrokerSeed = {
  name: string;
  category: string;
  tier: number; // 1 = Crucial, 2 = High, 3 = Standard
  searchUrl?: string;
  optOutUrl?: string;
  optOutMethod?: string;
  difficulty?: string;
  estProcessingDays?: number;
  alsoCovers?: string;
  parentCompany?: string;
  instructions?: string;
};

export const BROKER_SEED: BrokerSeed[] = [
  { name: "BeenVerified", category: "People Search", tier: 1, searchUrl: "https://www.beenverified.com/", optOutUrl: "https://www.beenverified.com/app/optout/search", optOutMethod: "Online Form + Email Confirm", difficulty: "Easy", estProcessingDays: 3, alsoCovers: "PeopleLooker, PeopleSmart", parentCompany: "PeopleConnect", instructions: "Also opt out of property search at /app/optout/address-search. One opt-out per email." },
  { name: "CheckPeople", category: "People Search", tier: 1, searchUrl: "https://checkpeople.com/privacy-rights", optOutUrl: "https://checkpeople.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5, instructions: "First request data copy under 'Right to Know'. Requires birthdate and full legal name." },
  { name: "Clustal", category: "People Search", tier: 1, searchUrl: "http://Clustal.org", optOutUrl: "https://www.clustal.org/privacy-control", optOutMethod: "Online Form + Email Confirm", difficulty: "Medium", estProcessingDays: 3, instructions: "Must grab URL from 'view full record' first. Different email needed per listing." },
  { name: "ClustrMaps", category: "People Search", tier: 1, searchUrl: "https://clustrmaps.com/", optOutUrl: "https://clustrmaps.com/bl/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5, instructions: "Check off all items associated with your account." },
  { name: "Intelius", category: "People Search", tier: 1, searchUrl: "https://www.intelius.com/", optOutUrl: "https://suppression.peopleconnect.us/login", optOutMethod: "Online Form / Email / Phone", difficulty: "Medium", estProcessingDays: 5, alsoCovers: "Addresses.com, Addresssearch.com, Anywho, Classmates, DateCheck, Instant Checkmate, InstantPeopleFinder, iSearch, LookUpAnyone, Peopleconnect.us, PeopleFinder, PeopleLookup, Phonesbook, Publicrecords, Spock, Truthfinder, US Search, Zabasearch", parentCompany: "PeopleConnect", instructions: "Email support@mailer.intelius.com or call 1-888-245-1655. Owns many subsidiaries." },
  { name: "Men Stopping Violence", category: "People Search", tier: 1, searchUrl: "https://www.menstoppingviolence.org/people/", optOutUrl: "https://www.menstoppingviolence.org/opt-out/", optOutMethod: "Online Form + Email Confirm", difficulty: "Easy", estProcessingDays: 3, instructions: "Search for name, grab URL, submit to opt-out page." },
  { name: "MyLife", category: "People Search", tier: 1, searchUrl: "https://www.mylife.com", optOutUrl: "https://www.mylife.com/privacyrequest", optOutMethod: "Online Form / Email / Phone", difficulty: "Hard", estProcessingDays: 30, alsoCovers: "Wink.com", instructions: "Email privacy@mylife.com. May require phone call to (888) 704-1900. Shows 'reputation scores'." },
  { name: "Nuwber", category: "People Search", tier: 1, searchUrl: "https://nuwber.com/", optOutUrl: "https://nuwber.com/removal/link", optOutMethod: "Online Form / Email", difficulty: "Medium", estProcessingDays: 7, instructions: "Use 'filter by state' to find your URL. Email support@nuwber.com if form fails." },
  { name: "Radaris", category: "People Search", tier: 1, searchUrl: "https://radaris.com/", optOutUrl: "https://radaris.com/control-privacy", optOutMethod: "Online Form / Email", difficulty: "Hard", estProcessingDays: 7, instructions: "Account creation required. Email customer-service@radaris.com if form fails. May need multiple follow-ups." },
  { name: "SmartBackgroundChecks", category: "People Search", tier: 1, searchUrl: "https://www.smartbackgroundchecks.com/", optOutUrl: "https://www.smartbackgroundchecks.com/optout", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 3, alsoCovers: "PeopleFinders", instructions: "Removal likely also removes from PeopleFinders." },
  { name: "Spokeo", category: "People Search", tier: 1, searchUrl: "https://www.spokeo.com/search", optOutUrl: "https://www.spokeo.com/optout", optOutMethod: "Online Form + Email Confirm", difficulty: "Easy", estProcessingDays: 3, alsoCovers: "FreePeopleDirectory", instructions: "Scroll to 'opt out your information' section. Paid accounts may retain data." },
  { name: "That's Them", category: "People Search", tier: 1, searchUrl: "https://thatsthem.com/", optOutUrl: "https://thatsthem.com/optout", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 3, instructions: "Do not click Spokeo identity theft link — it is a paid upsell." },
  { name: "Whitepages", category: "People Search", tier: 1, searchUrl: "https://www.whitepages.com/", optOutUrl: "https://www.whitepages.com/suppression_requests", optOutMethod: "Online Form + Phone Verify", difficulty: "Medium", estProcessingDays: 2, alsoCovers: "411.com, Whitepages Premium", instructions: "Requires automated phone call with 4-digit code. Also check Whitepages Premium. Owns 411.com." },
  { name: "Acxiom", category: "Marketing Data", tier: 2, searchUrl: "https://www.aboutthedata.com", optOutUrl: "https://www.acxiom.com/optout/", optOutMethod: "Online Form / Phone", difficulty: "Medium", estProcessingDays: 30, instructions: "Call (877) 774-2094. Suppresses from marketing use; won't delete all data. One of world's largest." },
  { name: "Advanced Background Checks", category: "People Search", tier: 2, searchUrl: "https://www.advancedbackgroundchecks.com", optOutUrl: "https://www.advancedbackgroundchecks.com/removal", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 3, instructions: "Leave city/state/age blank when searching." },
  { name: "Ancestry.com", category: "Genealogy", tier: 2, searchUrl: "https://www.ancestry.com/account/", optOutUrl: "https://support.ancestry.com/s/reportissue?language=en_US", optOutMethod: "Email / Online Form", difficulty: "Medium", estProcessingDays: 14, instructions: "Create free account, search records, copy URLs, email to privacy@ancestry.com." },
  { name: "FamilyTreeNow", category: "Genealogy", tier: 2, searchUrl: "https://www.familytreenow.com/", optOutUrl: "https://www.familytreenow.com/optout", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 3, instructions: "Search for yourself first, then submit removal." },
  { name: "FastPeopleSearch", category: "People Search", tier: 2, searchUrl: "https://www.fastpeoplesearch.com/", optOutUrl: "https://www.fastpeoplesearch.com/optout", optOutMethod: "Online Form + Email Confirm", difficulty: "Easy", estProcessingDays: 3, instructions: "May need to solve a CAPTCHA." },
  { name: "USPhoneBook", category: "People Search", tier: 2, searchUrl: "https://www.usphonebook.com/", optOutUrl: "https://www.usphonebook.com/opt-out/", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 3, instructions: "Search by phone number." },
  { name: "Archives.com", category: "People Search", tier: 3, searchUrl: "https://www.archives.com/", optOutUrl: "https://www.archives.com/Optout", optOutMethod: "Online Form", difficulty: "Medium", estProcessingDays: 7, instructions: "Must sign up for free trial first (then cancel), then opt out." },
  { name: "Classmates.com", category: "Social/Alumni", tier: 3, searchUrl: "https://www.classmates.com/", optOutUrl: "https://help.classmates.com/hc/en-us/articles/115002224171", optOutMethod: "Account Cancellation", difficulty: "Easy", estProcessingDays: 7, parentCompany: "PeopleConnect", instructions: "Cancel free or paid membership per instructions." },
  { name: "Cyber Background Checks", category: "People Search", tier: 3, searchUrl: "https://www.cyberbackgroundchecks.com/", optOutUrl: "https://www.cyberbackgroundchecks.com/removal", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5 },
  { name: "Facecheck.id", category: "Face Search", tier: 3, searchUrl: "https://facecheck.id/", optOutUrl: "https://facecheck.id/Face-Search/RemoveMyPhotos", optOutMethod: "Online Form + ID Upload", difficulty: "Medium", estProcessingDays: 7, instructions: "Requires uploading face photo + blurred ID. Removes from Facecheck only, not source sites." },
  { name: "FamilySearch", category: "Genealogy", tier: 3, searchUrl: "https://www.familysearch.org/", optOutUrl: "https://submit-irm.trustarc.com/services/validation/b8d6e704-e5b1-42a0-9f86-bbdec35939a1", optOutMethod: "Online Form + Email Verify", difficulty: "Medium", estProcessingDays: 14, instructions: "Create free account, search historical records, copy URLs, submit opt-out form." },
  { name: "FreePeopleDirectory", category: "People Search", tier: 3, searchUrl: "https://www.freepeopledirectory.com", optOutUrl: "https://www.spokeo.com/optout", optOutMethod: "Via Spokeo Opt-Out", difficulty: "Easy", estProcessingDays: 3, instructions: "Opt out handled through Spokeo's opt-out page." },
  { name: "InfoTracer", category: "People Search", tier: 3, searchUrl: "https://www.infotracer.com", optOutUrl: "https://infotracer.com/optout/", optOutMethod: "Online Form / Mail / Fax", difficulty: "Medium", estProcessingDays: 14, instructions: "Can also mail form or fax to 1-617-933-9946." },
  { name: "National Public Data", category: "People Search", tier: 3, searchUrl: "https://nationalpublicdata.com/search", optOutUrl: "https://nationalpublicdata.com/optout.html", optOutMethod: "Online Form + Email Confirm", difficulty: "Easy", estProcessingDays: 5, instructions: "Copy unique profile URL first, paste into opt-out form." },
  { name: "NeighborReport", category: "People Search", tier: 3, searchUrl: "https://neighbor.report/", optOutUrl: "https://neighbor.report/remove", optOutMethod: "Online Form + Email Confirm", difficulty: "Easy", estProcessingDays: 5, instructions: "Search by name, address, or phone number." },
  { name: "PeopleByName", category: "People Search", tier: 3, searchUrl: "https://www.peoplebyname.com/people", optOutUrl: "https://www.peoplebyname.com/remove.php", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5, instructions: "Opt out for each record individually." },
  { name: "PeopleSearchNow", category: "People Search", tier: 3, searchUrl: "https://www.peoplesearchnow.com/", optOutUrl: "https://www.peoplesearchnow.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5 },
  { name: "PimEyes", category: "Face Search", tier: 3, searchUrl: "https://pimeyes.com/", optOutUrl: "https://pimeyes.com/en/opt-out-request-form", optOutMethod: "Online Form + ID Upload", difficulty: "Hard", estProcessingDays: 14, instructions: "Requires face photo upload + blurred photo ID. Use Signal blur feature for ID." },
  { name: "PrivateEye", category: "People Search", tier: 3, searchUrl: "https://www.privateeye.com/", optOutUrl: "https://www.privateeye.com/removal", optOutMethod: "Online Form", difficulty: "Medium", estProcessingDays: 7, instructions: "Initiate opt-out, then fill out the record removal form sent to you." },
  { name: "PrivateRecords", category: "People Search", tier: 3, searchUrl: "https://www.privaterecords.net/name/landing", optOutUrl: "https://www.privaterecords.net/api/helper/optOutLight/search", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5, instructions: "Search by name and state." },
  { name: "PropertyRecs", category: "Property/Real Estate", tier: 3, searchUrl: "https://dashboard.propertyrecs.com/", optOutUrl: "https://dashboard.propertyrecs.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5, instructions: "Search by name and state on the opt-out page." },
  { name: "Rehold", category: "Property/Real Estate", tier: 3, searchUrl: "https://rehold.com/", optOutUrl: "https://rehold.com/", optOutMethod: "Online Form + CAPTCHA", difficulty: "Easy", estProcessingDays: 5, instructions: "Look up home address, click red 'remove' button. Requires name, email, CAPTCHA." },
  { name: "Searchbug", category: "People Search", tier: 3, searchUrl: "https://www.searchbug.com/", optOutUrl: "https://www.searchbug.com/contact-us.aspx", optOutMethod: "Contact Form / Phone / Fax", difficulty: "Hard", estProcessingDays: 14, instructions: "Requires paid account to search. Call (760) 454-7301 or fax (760) 454-7341." },
  { name: "SearchPeopleFree", category: "People Search", tier: 3, searchUrl: "https://www.searchpeoplefree.com/", optOutUrl: "https://www.searchpeoplefree.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5, instructions: "Search by name, phone, address, AND email address." },
  { name: "SearchQuarry", category: "People Search", tier: 3, searchUrl: "https://www.searchquarry.com/", optOutUrl: "https://members.searchquarry.com/removeMyData/", optOutMethod: "Online Form + Email Confirm", difficulty: "Easy", estProcessingDays: 5, instructions: "Click verification link in inbox to finalize." },
  { name: "Social Catfish", category: "People Search", tier: 3, searchUrl: "https://socialcatfish.com", optOutUrl: "https://socialcatfish.com/opt-out/", optOutMethod: "Online Form + Email Confirm", difficulty: "Medium", estProcessingDays: 7, instructions: "Record URL of each page with your info. Submit URL, email, phone, address separately." },
  { name: "SpyFly", category: "People Search", tier: 3, searchUrl: "https://www.spyfly.com", optOutUrl: "https://www.spyfly.com/help-center/remove-my-public-record", optOutMethod: "Online Form / Email", difficulty: "Medium", estProcessingDays: 14, instructions: "Email support@spyfly.com. Provide name, age, address, email. Verify SpyFly has your data first." },
  { name: "TruePeopleSearch.com", category: "People Search", tier: 3, searchUrl: "https://www.truepeoplesearch.com/", optOutUrl: "https://www.truepeoplesearch.com/removal", optOutMethod: "Online Form + CAPTCHA", difficulty: "Medium", estProcessingDays: 5, instructions: "Enter name, city/state, email. Solve multiple CAPTCHAs." },
  { name: "TruePeopleSearch.net", category: "People Search", tier: 3, searchUrl: "https://truepeoplesearch.net", optOutUrl: "https://docs.google.com/forms/d/e/1FAIpQLSeCPggzv4iXE20iUjcr6vdVWxBOblCyGwDLcO-jZA5j2YF5fQ/viewform", optOutMethod: "Google Form", difficulty: "Medium", estProcessingDays: 7, instructions: "Close extra pages the site opens. Do not click 'top rated background search' links." },
  { name: "TruthFinder", category: "People Search", tier: 3, searchUrl: "https://www.truthfinder.com/", optOutUrl: "https://www.truthfinder.com/opt-out/", optOutMethod: "Online Form + Email Confirm", difficulty: "Easy", estProcessingDays: 3, parentCompany: "PeopleConnect", instructions: "FTC complaint history. Owned by PeopleConnect/Intelius umbrella." },
  { name: "United States Phone Book", category: "People Search", tier: 3, searchUrl: "https://www.unitedstatesphonebook.com/search.php", optOutUrl: "https://www.unitedstatesphonebook.com/contact.php", optOutMethod: "Contact Form", difficulty: "Medium", estProcessingDays: 7, instructions: "Enter telephone number and zip code from listing to request removal." },
  { name: "UnMask", category: "People Search", tier: 3, searchUrl: "https://unmask.com/", optOutUrl: "https://unmask.com/opt-out/", optOutMethod: "Online Form + Email Confirm", difficulty: "Medium", estProcessingDays: 5, instructions: "Enter name, city, state. Solve CAPTCHAs. Confirm via email link." },
  { name: "USA People Search", category: "People Search", tier: 3, searchUrl: "https://www.usa-people-search.com/", optOutUrl: "https://www.usa-people-search.com/removal", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5 },
  { name: "Veripages", category: "People Search", tier: 3, searchUrl: "https://veripages.com/", optOutUrl: "https://veripages.com/inner/control-privacy", optOutMethod: "Online Form + CAPTCHA + Email", difficulty: "Medium", estProcessingDays: 7, instructions: "Enter profile URL, name, email. Fill CAPTCHA, confirm email link." },
  { name: "VoterRecords", category: "Public Records", tier: 3, searchUrl: "https://voterrecords.com/", optOutUrl: "https://voterrecords.com/", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 7, instructions: "Find info, scroll to bottom, click 'record opt-out' link. May receive verification link." },
  { name: "ZoomInfo", category: "Business/Professional", tier: 3, searchUrl: "https://www.zoominfo.com/", optOutUrl: "https://privacyrequest.zoominfo.com/remove/verify", optOutMethod: "Online Form + Email Code", difficulty: "Medium", estProcessingDays: 14, instructions: "Primarily business-focused. Opt out if email is on record — they email a code." },
  { name: "Epsilon", category: "Marketing Data", tier: 2, searchUrl: "https://www.epsilon.com/", optOutUrl: "https://us.epsilon.com/marketing-data-summary-request", optOutMethod: "Online Form / Email / Phone", difficulty: "Medium", estProcessingDays: 30, alsoCovers: "Conversant Media", instructions: "Email optout@epsilon.com with full name and mailing address. Call (866) 267-3861. Rigorous identity verification." },
  { name: "Oracle Data Cloud (BlueKai)", category: "Marketing Data", tier: 2, searchUrl: "https://www.oracle.com/", optOutUrl: "https://datacloudoptout.oracle.com/optout/", optOutMethod: "Online Form", difficulty: "Medium", estProcessingDays: 10, alsoCovers: "BlueKai, Datalogix", instructions: "Opt out of third-party sharing and offline data deletion. One request per household member." },
  { name: "LexisNexis", category: "Risk/Legal Data", tier: 2, searchUrl: "https://consumer.risk.lexisnexis.com/", optOutUrl: "https://consumer.risk.lexisnexis.com/opt", optOutMethod: "Online Form + ID Required", difficulty: "Hard", estProcessingDays: 30, instructions: "Used by employers, insurers, law enforcement. Requires documentation. Very comprehensive profiles." },
  { name: "CoreLogic", category: "Property Data", tier: 2, searchUrl: "https://www.corelogic.com/", optOutUrl: "https://optout.corelogic.com/", optOutMethod: "Online Form", difficulty: "Medium", estProcessingDays: 30, instructions: "Property and mortgage data broker. Used by insurers and lenders." },
  { name: "Verisk Marketing Solutions", category: "Insurance Data", tier: 2, optOutUrl: "Phone: 1-800-888-4213", optOutMethod: "Phone Only", difficulty: "Medium", estProcessingDays: 30, instructions: "Insurance industry data broker. Affects insurance pricing and pre-screening." },
  { name: "Equifax (Marketing)", category: "Credit/Financial", tier: 2, searchUrl: "https://www.equifax.com/", optOutUrl: "https://www.equifax.com/personal/credit-report-services/credit-freeze/", optOutMethod: "Online / Phone: 1-800-349-9960", difficulty: "Medium", estProcessingDays: 3, instructions: "Freeze credit AND opt out of marketing. Separate from credit reporting opt-out." },
  { name: "Experian (Marketing)", category: "Credit/Financial", tier: 2, searchUrl: "https://www.experian.com/", optOutUrl: "https://www.experian.com/privacy/center.html", optOutMethod: "Online / Phone: 1-888-397-3742", difficulty: "Medium", estProcessingDays: 3, instructions: "Opt out of marketing lists. Separate from credit freeze." },
  { name: "TransUnion (Marketing)", category: "Credit/Financial", tier: 2, searchUrl: "https://www.transunion.com/", optOutUrl: "https://www.transunion.com/optout", optOutMethod: "Online / Phone: 1-888-909-8872", difficulty: "Medium", estProcessingDays: 3, instructions: "Opt out of marketing and prescreened offers." },
  { name: "Innovis", category: "Credit/Financial", tier: 2, searchUrl: "https://www.innovis.com/", optOutUrl: "https://www.innovis.com/personal/securityFreeze", optOutMethod: "Online / Phone: 1-800-540-2505", difficulty: "Medium", estProcessingDays: 3, instructions: "4th major credit bureau. Freeze credit and opt out of marketing." },
  { name: "ChexSystems", category: "Banking Data", tier: 2, searchUrl: "https://www.chexsystems.com/", optOutUrl: "https://www.chexsystems.com/security-freeze/place-freeze", optOutMethod: "Online / Phone: 1-800-428-9623", difficulty: "Medium", estProcessingDays: 3, instructions: "Prevents approval of bank accounts in your name without consent." },
  { name: "SageStream", category: "Credit/Financial", tier: 3, searchUrl: "https://www.sagestreamllc.com/", optOutUrl: "https://www.sagestreamllc.com/security-freeze/", optOutMethod: "Online Form", difficulty: "Medium", estProcessingDays: 14, instructions: "Alternative credit reporting agency. Used for thin-file consumers." },
  { name: "OptOutPrescreen.com", category: "Prescreened Offers", tier: 2, searchUrl: "https://www.optoutprescreen.com/", optOutUrl: "https://www.optoutprescreen.com/", optOutMethod: "Online Form (permanent requires mail)", difficulty: "Easy", estProcessingDays: 5, instructions: "Official industry site. Opt out of prescreened credit and insurance offers. Permanent opt-out requires mailed form." },
  { name: "Do Not Call Registry", category: "Telemarketing", tier: 2, searchUrl: "https://www.donotcall.gov", optOutUrl: "https://www.donotcall.gov", optOutMethod: "Online Registration", difficulty: "Easy", estProcessingDays: 31, parentCompany: "FTC", instructions: "Register all phone numbers. Takes up to 31 days to take effect." },
  { name: "DMAChoice", category: "Direct Mail", tier: 3, searchUrl: "https://dmachoice.org/", optOutUrl: "https://dmachoice.org/static/consumer_choice_tools.php", optOutMethod: "Online Form (fee)", difficulty: "Easy", estProcessingDays: 90, instructions: "Removes from prospective mailers. Does not cover political mail or recent business contacts." },
  { name: "PaperKarma", category: "Direct Mail", tier: 3, optOutUrl: "https://www.paperkarma.com/product/paperkarma-subscription/", optOutMethod: "App-based (subscription)", difficulty: "Easy", estProcessingDays: 30, instructions: "Removes from direct mail vendors including charity solicitations and catalogs." },
  { name: "CatalogChoice", category: "Direct Mail", tier: 3, searchUrl: "https://www.catalogchoice.org/", optOutUrl: "https://www.catalogchoice.org/", optOutMethod: "Online (free account)", difficulty: "Easy", estProcessingDays: 30, instructions: "Cancel unwanted catalogs. Free service." },
  { name: "Valpak", category: "Direct Mail", tier: 3, searchUrl: "https://www.valpak.com/", optOutUrl: "https://www.valpak.com/remove-address", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 30, instructions: "Remove address from coupon pack mailings. Free." },
  { name: "Google – Results About You", category: "Search Engine", tier: 1, searchUrl: "https://myaccount.google.com/", optOutUrl: "https://support.google.com/websearch/answer/12719076", optOutMethod: "Online Tool", difficulty: "Easy", estProcessingDays: 14, parentCompany: "Google", instructions: "Free service to find and request deindexing of personal data from Google Search." },
  { name: "Google – Content Removal", category: "Search Engine", tier: 1, searchUrl: "https://www.google.com/", optOutUrl: "https://support.google.com/websearch/troubleshooter/3111061", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 14, parentCompany: "Google", instructions: "Remove doxxing info, non-consensual images, exploitative removal site content." },
  { name: "Bing – Content Removal", category: "Search Engine", tier: 2, searchUrl: "https://www.bing.com/", optOutUrl: "https://www.microsoft.com/en-ca/concern/bing", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 14, parentCompany: "Microsoft", instructions: "Remove contact info and other personal data from Bing search results." },
  { name: "411.com", category: "People Search", tier: 3, searchUrl: "https://www.411.com/", optOutUrl: "https://www.whitepages.com/suppression_requests", optOutMethod: "Via Whitepages Opt-Out", difficulty: "Easy", estProcessingDays: 2, parentCompany: "Whitepages", instructions: "Owned by Whitepages. Same opt-out process." },
  { name: "411 Locate", category: "People Search", tier: 3, searchUrl: "https://www.411locate.com/", optOutUrl: "https://www.411locate.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5 },
  { name: "ArrestFacts", category: "Arrest Records", tier: 3, searchUrl: "https://www.arrestfacts.com/", optOutUrl: "https://www.arrestfacts.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 7, instructions: "Arrest and mugshot data broker." },
  { name: "Arrests.org", category: "Arrest Records", tier: 3, searchUrl: "https://arrests.org/", optOutUrl: "https://arrests.org/opt-out/", optOutMethod: "Online Form", difficulty: "Medium", estProcessingDays: 14, instructions: "Mugshot and arrest records. May require fee for some removals." },
  { name: "BlockShopper", category: "Property/Real Estate", tier: 3, searchUrl: "https://blockshopper.com/", optOutUrl: "https://blockshopper.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 7, instructions: "Real estate transaction data." },
  { name: "CocoFinder", category: "People Search", tier: 3, searchUrl: "https://cocofinder.com/", optOutUrl: "https://cocofinder.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5 },
  { name: "Dynata", category: "Marketing Data", tier: 3, searchUrl: "https://www.dynata.com/", optOutUrl: "https://www.dynata.com/opt-out/", optOutMethod: "Online Form / Phone", difficulty: "Medium", estProcessingDays: 30, instructions: "Survey and market research data. Known for robocalls." },
  { name: "Florida Resident DB", category: "State Records", tier: 3, searchUrl: "https://www.floridaresident.com/", optOutUrl: "https://www.floridaresident.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 7, instructions: "Florida-specific public records aggregator." },
  { name: "Homemetry", category: "Property/Real Estate", tier: 3, searchUrl: "https://homemetry.com/", optOutUrl: "https://homemetry.com/control/privacy", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 7, instructions: "Home and property data." },
  { name: "IdTrue", category: "People Search", tier: 3, searchUrl: "https://www.idtrue.com/", optOutUrl: "https://www.idtrue.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5 },
  { name: "Michigan Resident DB", category: "State Records", tier: 3, searchUrl: "https://www.michiganresidentdatabase.com/", optOutUrl: "https://www.michiganresidentdatabase.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 7, instructions: "Michigan-specific public records aggregator." },
  { name: "Mugshots.com", category: "Arrest Records", tier: 3, searchUrl: "https://mugshots.com/", optOutUrl: "https://mugshots.com/opt-out.html", optOutMethod: "Online Form", difficulty: "Medium", estProcessingDays: 14, instructions: "May charge fee for removal. Check state laws for leverage." },
  { name: "NeighborWho", category: "People Search", tier: 3, searchUrl: "https://www.neighborwho.com/", optOutUrl: "https://www.neighborwho.com/app/optout/search", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 3, parentCompany: "PeopleConnect", instructions: "Owned by BeenVerified/PeopleConnect." },
  { name: "North Carolina Resident DB", category: "State Records", tier: 3, searchUrl: "https://www.northcarolinaresidentdatabase.com/", optOutUrl: "https://www.northcarolinaresidentdatabase.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 7, instructions: "NC-specific public records aggregator." },
  { name: "NuMLookup", category: "Phone Lookup", tier: 3, searchUrl: "https://www.numlookup.com/", optOutUrl: "https://www.numlookup.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5, instructions: "Phone number lookup database." },
  { name: "Ohio Resident DB", category: "State Records", tier: 3, searchUrl: "https://www.ohioresidentdatabase.com/", optOutUrl: "https://www.ohioresidentdatabase.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 7, instructions: "Ohio-specific public records aggregator." },
  { name: "OfficialUSA.com", category: "People Search", tier: 3, searchUrl: "https://www.officialusa.com/", optOutUrl: "https://www.officialusa.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5 },
  { name: "OkCaller", category: "Phone Lookup", tier: 3, searchUrl: "https://www.okcaller.com/", optOutUrl: "https://www.okcaller.com/remove.php", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5, instructions: "Reverse phone lookup." },
  { name: "Ownerly", category: "Property/Real Estate", tier: 3, searchUrl: "https://www.ownerly.com/", optOutUrl: "https://www.ownerly.com/opt-out", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5, parentCompany: "PeopleConnect", instructions: "Property data. Owned by PeopleConnect." },
  { name: "SpyDialer", category: "Phone Lookup", tier: 3, searchUrl: "https://spydialer.com/", optOutUrl: "https://spydialer.com/optout.aspx", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5, instructions: "Reverse phone and voicemail lookup." },
  { name: "TrueCaller", category: "Phone Lookup", tier: 3, searchUrl: "https://www.truecaller.com/", optOutUrl: "https://www.truecaller.com/unlisting", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 24, instructions: "Global caller ID database. Takes up to 24 hours." },
  { name: "ZabaSearch", category: "People Search", tier: 3, searchUrl: "https://www.zabasearch.com/", optOutUrl: "https://www.zabasearch.com/block_records/", optOutMethod: "Online Form", difficulty: "Easy", estProcessingDays: 5, parentCompany: "PeopleConnect", instructions: "Owned by Intelius/PeopleConnect." },
  { name: "Have I Been Pwned", category: "Data Breach Check", tier: 1, searchUrl: "https://haveibeenpwned.com/", optOutUrl: "https://haveibeenpwned.com/", optOutMethod: "Monitoring Only", difficulty: "Easy", estProcessingDays: 0, instructions: "Check if email was in a data breach. Free monitoring service — not a removal but essential intelligence." },
  { name: "OpenNPI (Healthcare)", category: "Healthcare", tier: 3, searchUrl: "https://opennpi.com/provider/", optOutUrl: "https://opennpi.com/contact", optOutMethod: "Contact Form", difficulty: "Medium", estProcessingDays: 14, alsoCovers: "Doximity", instructions: "For healthcare workers with NPI numbers. Update or remove contact info." },
];

// Map a broker's tier to a riskLevel for the legacy `riskLevel` column.
export function riskForTier(tier: number): string {
  return tier === 1 ? "high" : tier === 2 ? "medium" : "low";
}
